accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout"),
    path('login/', views.login, name="login"),
    #path('delete/', views.delete, name="delete"),
]

prowebtooner/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers_user")
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings_user")

accounts/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

User = get_user_model()

class UserCustomCreationForm(UserCreationForm):
	
	email = forms.EmailField(
		label ="이메일",
		required=True,
		help_text='example@example.com 의 형식으로 입력해주세요',
		error_messages={
			'required':'이메일을 입력해주세요',
			'invalid':'이메일 형식이 잘못되었습니다.',
		},
		max_length=30,
		widget=forms.EmailInput(
			attrs={
				'class': 'form-control mb-2',
				'placeholder': '이메일을 입력해주세요',
			}
		),
	)

	username = forms.CharField(
		label = "닉네임",
		required = True,
		help_text='최대 20 자까지 입력 가능합니다',
		error_messages={
			'required' : '닉네임을 입력해주세요',
			'invalid' : '닉네임 형식이 잘못되었습니다',
		},
		max_length=20,
		widget=forms.TextInput(
			attrs={
				'class': 'form-control mb-2',
				'placeholder':'닉네임을 입력해주세요',
			}
		),
	)

	password1 = forms.CharField(
		label = "비밀번호",
		required = True,
		help_text='최소한 8 글자, 최대 20글자까지 설정가능합니다',
		max_length=20,
		min_length=8,
		error_messages={
			'required':'비밀번호를 입력해주세요',
			'max_length':'비밀번호 글자 수가 20을 초과하셨습니다',
			'min_length':'비밀번호는 최소한 8 글자 이상 입력해주세요',
		},
		widget=forms.PasswordInput(
			attrs={
				'placeholder':'비밀번호를 입력해주세요',
				'class':'form-control mb-2',
			}
		),
	)
	
	password2 = forms.CharField(
		label = "비밀번호 확인",
		required = True,
		max_length=20,
		min_length=8,
		error_messages={
			'required':'비밀번호를 재확인해주세요',
		},
		widget=forms.PasswordInput(
			attrs={
				'placeholder':'비밀번호를 다시 입력해주세요',
				'class':'form-control mb-2',
			}
		),
	)
	
	first_name = forms.CharField(
		label = "이름",
		required = False,
		help_text='필수사항이 아닙니다',
		max_length = 20,
		min_length = 1,
		widget=forms.TextInput(
			attrs={
				'placeholder':'이름을 입력해주세요',
				'class':'form-control mb-2',
			}
		),
	)
	last_name = forms.CharField(
		label = "성",
		required = False,
		max_length = 20,
		min_length = 1,
		help_text='필수사항이 아닙니다',
		widget=forms.TextInput(
			attrs={
				'placeholder':'성을 입력해주세요',
				'class':'form-control mb-2',
			}
		),
	)
	
	def clean_username(self):
		username = self.cleaned_data['username'].lower()
		r = User.objects.filter(username=username)
		if r.count():
				raise  ValidationError("이미 존재하는 닉네임입니다")
		return username
	
	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		r = User.objects.filter(email=email)
		if r.count():
			raise ValidationError("이미 존재하는 이메일입니다")
		return email
	
	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		
		if password1 and password1 and password1 != password2:
			raise ValidationError("비밀번호를 다시 확인해주세요")
		
		return password2
	
	# def save(self, commit=True):
	# 	user = User.objects.create_user(
	# 		self.cleaned_data['username'],
	# 		self.cleaned_data['email'],
	# 		self.cleaned_data['password1'],
	# 		self.cleaned_data['first_name'],
	# 		self.cleaned_data['last_name'],
	# 	)
	
	class Meta:
		model = get_user_model()
		fields = ('email', 'username', 'first_name', 'last_name',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import User
from .forms import UserCustomCreationForm

# Create your views here.
def mainpage(request):
	form = UserCreationForm()
	
	return render(request, 'accounts/mainpage.html', {
		'form':form,
	})

def signup(request):
    #회원 가입
    if request.method == "POST":
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('mainpage')
    else:
        form = UserCustomCreationForm()
        
    return render(request, 'accounts/signup.html', {
        'form':form,
    })
    
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return render(request, 'accounts/mainpage.html')
        else:
            return redirect('accounts:login')
    else:
        #유저로부터 username 과 비밀번호를 받는다.
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {
            'form':form,
        })

def logout(request):
    auth_logout(request)
    return redirect('mainpage')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1>로그인</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="mx-2 btn btn-primary">로그인</button>
    {% endbuttons %}
    <!--{{ form }}-->
</form>

{% endblock %}

accounts/templates/accounts/mainpage.html
{% extends 'base.html' %}

{% block body %}



{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load bootstrap4 %}

{% block body %}
<h1 class='mx-4'>회원가입</h1>
<form method="POST">
	{% csrf_token %}
	
	{% for field in form.visible_fields %}
	<div class="form-group mx-2 col-6">
		<label for="{{ field.id_for_label}}">{{field.label}}</label>
		{{ field }}
		{% if field.help_text %}
			<small class="form-text text-muted">
				{{field.help_text}}
			</small>
		{% endif %}
		{% for error in field.errors %}
			<span class="help-block">{{ error }}</span>
		{% endfor %}
	</div>
	
	{% endfor %}
	
	{% buttons %}
	<button type="submit" class="mx-4 btn btn-primary" style="background-color: #689339; border-color: #689339">
		회원가입
	</button>
	{% endbuttons %}

</form>

{% endblock %}

prowebtooner/templates/_nav.html
{% load widget_tweaks %}
{% load bootstrap4 %}

<nav class="col-sm-3 navbar navbar-auto navbar-light mb-4" style="background-color:#8BB460">
	<a class="navbar-brand" style="color:#ECF6E1" href="{% url 'mainpage' %}">HOME</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav" style="border-color:#689339">
		<ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link disabled text-white" href="#">{{ user }}</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link text-white" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
			{% else %}
            <li class="nav-item">
              <a class="nav-link" style="color:#ECF6E1" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
              <!-- <a class="nav-link" style="color:#ECF6E1" href="{% url 'accounts:login' %}">로그인</a> -->
                <a class="nav-link" style="color:#ECF6E1" data-toggle="modal" data-target="#loginModal">로그인</a>
            </li>
			{% endif %}
		</ul>
	</div>
</nav>


<!-- 로그인 모달 -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">
                    로그인
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}

                    {% for field in form.visible_fields %}
                    <div class="form-group mx-2 col-6">
                        {% if field.label != "비밀번호 확인" %}
                            <label for="{{ field.id_for_label}}">{{field.label}}</label>
                            {{ field }}
                            <!-- {% if field.help_text %}
                                <small class="form-text text-muted">
                                    {{field.help_text}}
                                </small>
                            {% endif %} -->
                            {% for error in field.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>

                    {% endfor %}

                    {% buttons %}
                    <button type="submit" class="mx-4 btn btn-primary">
                        로그인
                    </button>
                    {% endbuttons %}

                </form>
            </div>
        </div>
    </div>
</div>

prowebtooner/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
		<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<!-- FontAwesome -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
		
		<!-- FIREBASE CDN -->
		<script src="https://cdn.firebase.com/libs/firebaseui/3.5.2/firebaseui.js"></script>
		<link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/3.5.2/firebaseui.css" />
    <!-- 스크립트 -->
    <style>
        
    </style>
  </head>
  <body style="background-color:#ECF6E1">
    {% include '_nav.html' %}
		
    {% block body %}
    

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<!-- Firebase -->
		<script src="https://www.gstatic.com/firebasejs/5.9.4/firebase.js"></script>
		<script>
			// Initialize Firebase
			var config = {
				apiKey: "AIzaSyA19GR68b7_CKrD2tLrtNesXdyiF_6VGAI",
				authDomain: "breaking-interview.firebaseapp.com",
				databaseURL: "https://breaking-interview.firebaseio.com",
				projectId: "breaking-interview",
				storageBucket: "breaking-interview.appspot.com",
				messagingSenderId: "521170743259"
			};
			firebase.initializeApp(config);
		</script>
  </body>
</html>